[scripts] fix (un)mountmenu scripts

diff --git a/scripts/mountmenu b/scripts/mountmenu
--- a/scripts/mountmenu
+++ b/scripts/mountmenu
@@ -1,18 +1,24 @@
 #!/bin/sh
 
-device=$(lsblk -rnpo 'NAME,SIZE,TYPE,MOUNTPOINT' | awk '$3=="part"&&$4==""{printf "%s (%s)",$1,$2}' | dmenu -i -l 10 -p 'Choose device' | awk '{print $1}')
+available_devices=$(lsblk -rnpo 'NAME,SIZE,TYPE,MOUNTPOINT' | awk '$3=="part"&&$4==""{printf "%s (%s)",$1,$2}')
+if [ -z "$available_devices" ]; then
+	notify-send -a 'device manager' 'no devices found'
+	exit 0
+fi
+
+device=$(echo "$available_devices" | dmenu -i -l 10 -p 'Choose device' | awk '{print $1}')
 [ -z "$device" ] && exit 1
 
 mountpoint=$(find /mnt /media /mount ~ -maxdepth 5 -not -path '*/\.*' -type d -empty 2>/dev/null | sed "s|^$HOME|~|" | dmenu -i -l 30 -p 'Choose mountpoint' | sed "s|^~|$HOME|")
-[ ! $mountpoint ] && exit 1
+[ -z "$mountpoint" ] && exit 1
 
 if [ ! -d $mountpoint ]; then
-	(mkdir -p $mountpoint || sudo -A mkdir -p $mountpoint) || (notify-send -a "Device mount menu" "Error mounting device" "Could not create directory: $mountpoint" & exit 2)
+	(mkdir -p $mountpoint || sudo -A mkdir -p $mountpoint) || notify-send -a "device manager" "Error mounting device" "Could not create directory: $mountpoint" & exit 2
 fi
 
-tmpfile=$(tempfile)
+tmpfile=$(mktemp)
 (sudo -A mount $device $mountpoint 2>$tmpfile) &&
 	(rm $tmpfile ; pgrep dunst >/dev/null && 
-		notify-send -a 'Device mount menu' "Successfully mounted device" "$device was mounted to $(echo -n $mountpoint | sed "s|^$HOME|~|")") ||
-	(pgrep dunst >/dev/null && notify-send -a 'Device mount menu' "Error mounting device" "$device could not be mounted to $(echo -n $mountpoint | sed "s|^$HOME|~|").\nOpening the error file..." ; 
+		notify-send -a 'device manager' "Successfully mounted device" "$device was mounted to $(echo -n $mountpoint | sed "s|^$HOME|~|")") ||
+	(pgrep dunst >/dev/null && notify-send -a 'device manager' "Error mounting device" "$device could not be mounted to $(echo -n $mountpoint | sed "s|^$HOME|~|").\nOpening the error file..." ; 
 		$TERMINAL -e less $tmpfile &)
diff --git a/scripts/unmountmenu b/scripts/unmountmenu
--- a/scripts/unmountmenu
+++ b/scripts/unmountmenu
@@ -1,26 +1,26 @@
 #!/bin/sh
 
 available=$(lsblk -rnpo 'NAME,SIZE,MOUNTPOINT' | awk '$3!=""&&$3!="/"&&$3!="/boot"&&$3!="/home"&&$3!="/back"&&$3!="[SWAP]"{printf "%s (%s)\n",$1,$2}')
-if [ ! $available ]; then 
-	notify-send -a "Device unmount menu" "No devices available" "There are no devices which can be safely unmounted" & exit 2
+if [ -z "$available" ]; then 
+	notify-send -a "device manager" "No devices available" "There are no devices which can be safely unmounted" & exit 2
 fi
 
 device=$(echo -n "$available" | dmenu -i -l 10 -p 'Choose device:' | awk '{print $1}')
 [ -z "$device" ] && exit 1
 if [ ! -b $device ]; then
-	notify-send -a "Device mount menu" "Error mounting device" "The specified device does not exist:\n$device" &
+	notify-send -a "Device mount menu" "Error unmounting device" "The specified device does not exist:\n$device" &
 	exit 2
 fi
 
 mountpoint=$(lsblk -rnpo 'NAME,MOUNTPOINT' | awk "\$1==\"$device\"{print \$2}" | sed "s|^$HOME|~|")
-deletemp=$(printf "Yes\\nNo" | dmenu -p "Delete mountpoint? ($mountpoint)" | sed 's/Yes\|yes\|Y\|y/1/; s/No\|no\|N\|n/0/')
+deletemp=$(printf "Yes\\nNo" | dmenu -p "Delete mountpoint? ($mountpoint)" | grep -io 'y\(es\)\?\|no\?' | head -n1 | sed 's/Yes\|yes\|Y\|y/1/; s/No\|no\|N\|n/0/')
 
-tmpfile=$(tempfile)
+tmpfile=$(mktemp)
 (sudo -A umount $device 2>$tmpfile) &&
-	(rm -f $tmpfile ; pgrep -x dunst >/dev/null && notify-send -a "Device unmount menu" "Device was unmounted" "$device was successfully unmounted" &) ||
-	((pgrep -x dunst >/dev/null && notify-send -a "Device unmount menu" "Error unmounting device" "$device could not be unmounted.\nOpening error output...") ; $TERMINAL -e less $tmpfile & cpid=$! ; (wait $cpid && rm -f $tmpfile) &)
+	(rm -f $tmpfile ; pgrep -x dunst >/dev/null && notify-send -a "device manager" "Device was unmounted" "$device was successfully unmounted" &) ||
+	((pgrep -x dunst >/dev/null && notify-send -a "device manager" "Error unmounting device" "$device could not be unmounted.\nOpening error output...") ; $TERMINAL -e less $tmpfile & cpid=$! ; (wait $cpid && rm -f $tmpfile) &)
 
 [ $deletemp -eq 1 ] &&
 	(mountpoint=$(echo -n $mountpoint | sed "s|^~|$HOME|"); rm -rf $mountpoint || sudo -A rm -rf $mountpoint ||
-		(notify-send -a "Device unmount menu" "Could not delete mountpoint" "The directory $(echo -n $mountpoint | sed "s|^$HOME|~|") could not be deleted" & exit 3)
+		(notify-send -a "device manager" "Could not delete mountpoint" "The directory $(echo -n $mountpoint | sed "s|^$HOME|~|") could not be deleted" & exit 3)
 	)
